cloudmesh:
  cluster:
    aws:
      kind: kubernetes #| kubernetes
      size: SMALL #| MEDIUM | LARGE | XLARGE | CUSTOM
      nodegroups:
        - name: workers01
          instanceType: t2.micro # instance type
          desiredCapacity: 1 # number of nodes
          volumeSize: 28 #min size for EKS 20 GB, for PCS 128 GB
          capacityType: 'SPOT' # SPOT or ONDEMAND
