cloudmesh:
  cluster:
    aws: 
        nodegroups:
          - name: workers
            instanceType: t2.micro # instance type
            desiredCapacity: 2 # number of nodes
            volumeSize: 20 #min size in GB
            capacityType: 'SPOT' # SPOT or ON_DEMAND
